export const ProductService = {
  getProductsData() {
    return [
      {
        id: "1000",
        code: "f230fh0g3",
        name: "Bamboo Watch",
        description: "Product Description",
        image: "bamboo-watch.jpg",
        price: 65,
        category: "Accessories",
        quantity: 24,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
      {
        id: "1001",
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1002",
        code: "zz21cz3c1",
        name: "Blue Band",
        description: "Product Description",
        image: "blue-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 40,
        inventoryStatus: "LOWSTOCK",
        rating: 3,
      },
      {
        id: "1003",
        code: "244wgerg2",
        name: "Blue T-Shirt",
        description: "Product Description",
        image: "blue-t-shirt.jpg",
        price: 29,
        category: "Clothing",
        quantity: 25,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
      {
        id: "1004",
        code: "h456wer53",
        name: "Galaxy Earbuds",
        description: "Product Description",
        image: "galaxy-earbuds.jpg",
        price: 99,
        category: "Electronics",
        quantity: 64,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1005",
        code: "av2231fwg",
        name: "Brown Purse",
        description: "Product Description",
        image: "brown-purse.jpg",
        price: 120,
        category: "Accessories",
        quantity: 30,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1006",
        code: "bib36pfvm",
        name: "Green Backpack",
        description: "Product Description",
        image: "green-backpack.jpg",
        price: 45,
        category: "Accessories",
        quantity: 8,
        inventoryStatus: "LOWSTOCK",
        rating: 4,
      },
      {
        id: "1007",
        code: "mbvjkgip5",
        name: "Galaxy Phone",
        description: "Product Description",
        image: "galaxy-phone.jpg",
        price: 650,
        category: "Electronics",
        quantity: 23,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
      {
        id: "1008",
        code: "vbb124btr",
        name: "Gaming Set",
        description: "Product Description",
        image: "gaming-set.jpg",
        price: 95,
        category: "Electronics",
        quantity: 63,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
      {
        id: "1009",
        code: "vbb124btr",
        name: "Gaming Set",
        description: "Product Description",
        image: "gaming-set.jpg",
        price: 95,
        category: "Electronics",
        quantity: 63,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
    ];
  },
};
